language: node_js
node_js:
- '6'
- '7'
install:
- npm install
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: AfuxOeQKRcbgl8a8jst11lrCwP7xqiTUamTAa5Vc1ikjI2lUi7QVFl14N/Cb8o3PHzD9f3dKFdO8izzwDK55rgb4cSMUSIcSAJjEgSXIlw/jHLLPMZuB1jgwgEFIcHXm21kyUriBk9UNI6uwHIeIHyjyaZDt4LrplGbcKaoU6QASTpKN8h0e+j7RFHf6GYi07Fi8+IyTwjzHtaxZ84MnldrKkmAkR5OX6ISV5zO/TzZO0OHZ3+fKdUQTxqFw56CPZyucFgbWWc09BJ7+5mghy5v9j3A6Tk4bBAwDk2ckcu9i71gRW1M/9anWdxGk2rXRqd4/vBp2nU5lTrRbdp8oGbqADafbl8blD7GCRbHNkATWUe/Ps8KJ7m57Rk4fJdnb40JsdAkoN6hehTU7G2AB5WoYmUT3yOQ/xdVceb+CJ1MvLlF4YNkBf85URG/yUnb/7B/gyBwjrWtULokp5Ae9s3CPFzBEfgomD6hI6WyfpG/Tg6cTom+8YoUy6yvKN4mA0MQbRdcDXDS4z0+wu+RrD/Gc2PvCGgpIgEuMlIYs0UtcBcB08sF8BDTq88mLmoKX5GaXj5LJqSJieADL2+JiziScXy+lQEMv/oeekkQ+fqHgtTl0ab8Vt0Ed/44cfXIkF6EboxCnU9S+RRjlqeoCry55bXwaNNR+Buql/Um7EAE=
  app: mars-images
  skip_cleanup: true
  on:
    repo: sagar12861/mars
